package prices

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CatalogURL is the public price catalogue OpenCode itself uses.
const CatalogURL = "https://models.dev/api.json"

// catalogURL is the address actually fetched; a variable so tests can point at
// a local fixture instead of reaching the network.
var catalogURL = CatalogURL

// DefaultProviders mirrors tools/gen_prices.py. models.dev carries 200+
// providers, most of them niche gateways republishing the same models at
// different rates; a curated set avoids duplicate ids with conflicting prices.
var DefaultProviders = []string{
	"anthropic", "openai", "google", "google-vertex", "azure",
	"amazon-bedrock", "mistral", "deepseek", "xai", "groq", "cerebras",
	"openrouter", "github-copilot", "opencode", "alibaba", "fireworks-ai",
	"togetherai", "deepinfra",
}

// fetchTimeout bounds the whole download. The payload is ~4 MB.
const fetchTimeout = 90 * time.Second

// providerEntry is the subset of one models.dev provider we consume.
type providerEntry struct {
	Models map[string]struct {
		Name string `json:"name"`
		Cost *struct {
			Input      float64 `json:"input"`
			Output     float64 `json:"output"`
			CacheRead  float64 `json:"cache_read"`
			CacheWrite float64 `json:"cache_write"`
		} `json:"cost"`
	} `json:"models"`
}

// skipValue consumes the next JSON value without materialising it, so
// unwanted providers cost only the bytes needed to find their end.
func skipValue(dec *json.Decoder) error {
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	if _, ok := tok.(json.Delim); !ok {
		return nil // scalar: already consumed
	}
	// Objects and arrays: walk to the matching close delimiter.
	depth := 1
	for depth > 0 {
		t, err := dec.Token()
		if err != nil {
			return err
		}
		if dd, ok := t.(json.Delim); ok {
			switch dd {
			case '{', '[':
				depth++
			case '}', ']':
				depth--
			}
		}
	}
	return nil
}

// FetchCatalog downloads the live price catalogue and returns it in the
// on-disk document shape.
//
// Prices move: a sample comparison found ~2% of entries changed within four
// days, so a table that is only regenerated by hand drifts silently. Silent
// drift is the worst failure for a cost meter, because the number still looks
// authoritative.
func FetchCatalog(providers []string) (map[string]Rate, error) {
	if len(providers) == 0 {
		providers = DefaultProviders
	}
	req, err := http.NewRequest(http.MethodGet, catalogURL, nil)
	if err != nil {
		return nil, err
	}
	// models.dev answers 403 to the default Go user agent.
	req.Header.Set("User-Agent", "opencode-odometer/1.0 (+https://github.com)")
	req.Header.Set("Accept", "application/json")

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		io.Copy(io.Discard, resp.Body)
		return nil, fmt.Errorf("catalog: status %d", resp.StatusCode)
	}

	want := make(map[string]bool, len(providers))
	for _, p := range providers {
		want[p] = true
	}

	// Stream provider-by-provider rather than unmarshalling the whole
	// document. models.dev carries 200+ providers and we keep 18, so decoding
	// everything allocated ~20 MB to retain a fraction of it. Token-level
	// decoding lets an unwanted provider be skipped without ever building its
	// object graph.
	dec := json.NewDecoder(resp.Body)
	if tok, err := dec.Token(); err != nil {
		return nil, fmt.Errorf("catalog: %w", err)
	} else if d, ok := tok.(json.Delim); !ok || d != '{' {
		return nil, fmt.Errorf("catalog: expected a JSON object at the top level")
	}

	models := map[string]Rate{}
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return nil, fmt.Errorf("catalog: %w", err)
		}
		pid, _ := keyTok.(string)
		if !want[pid] {
			// Consume and discard this provider's value without decoding it.
			if err := skipValue(dec); err != nil {
				return nil, fmt.Errorf("catalog: %w", err)
			}
			continue
		}
		var prov providerEntry
		if err := dec.Decode(&prov); err != nil {
			return nil, fmt.Errorf("catalog %s: %w", pid, err)
		}
		for mid, m := range prov.Models {
			// An entry with no cost block cannot be accounted for. Skip rather
			// than invent a rate that would later look authoritative.
			if m.Cost == nil {
				continue
			}
			name := m.Name
			if name == "" {
				name = mid
			}
			key := pid + "/" + mid
			r := Rate{
				Name:       name,
				Family:     InferFamily(key),
				Input:      m.Cost.Input,
				Output:     m.Cost.Output,
				CacheRead:  m.Cost.CacheRead,
				CacheWrite: m.Cost.CacheWrite,
			}
			if looksFree(mid, r) {
				r.Free = true
			}
			models[key] = r
		}
	}
	if len(models) == 0 {
		return nil, fmt.Errorf("catalog: no models for the configured providers")
	}
	return models, nil
}

// looksFree mirrors the generator: an explicit free/sovereign marker, or no
// charge on any axis.
func looksFree(modelID string, r Rate) bool {
	low := strings.ToLower(modelID)
	if strings.HasSuffix(low, "-free") || strings.Contains(low, "sovereign") ||
		strings.Contains(low, "-free-") {
		return true
	}
	return r.Input <= 0 && r.Output <= 0 && r.CacheRead <= 0 && r.CacheWrite <= 0
}

// WriteCatalog saves a fetched table to path atomically, preserving the
// reference model so savings calculations survive a refresh.
func WriteCatalog(path string, models map[string]Rate, reference string) error {
	if reference == "" {
		reference = FallbackReference
	}
	doc := struct {
		Comment   string          `json:"_comment"`
		Source    string          `json:"_source"`
		Fetched   string          `json:"_fetched"`
		Reference string          `json:"reference_model"`
		Models    map[string]Rate `json:"models"`
	}{
		Comment: "USD per 1,000,000 tokens. Fetched from models.dev by the " +
			"odometer. Private/reseller rates belong in prices.local.json, " +
			"which is merged on top and survives a refresh.",
		Source:    CatalogURL,
		Fetched:   time.Now().UTC().Format(time.RFC3339),
		Reference: reference,
		Models:    models,
	}
	raw, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	if dir := filepath.Dir(path); dir != "" {
		_ = os.MkdirAll(dir, 0o755)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append(raw, '\n'), 0o644); err != nil {
		return err
	}
	// Atomic: a reader must never observe a half-written table.
	return os.Rename(tmp, path)
}

// Refresh fetches the catalogue, writes it to the primary table and reloads.
// The private overlay is re-applied by Reload, so user rates are never lost.
func (b *Book) Refresh() (int, error) {
	b.mu.RLock()
	primary, reference := b.primary, b.ReferenceModel
	b.mu.RUnlock()
	if primary == "" {
		return 0, fmt.Errorf("no price table path configured")
	}

	models, err := FetchCatalog(nil)
	if err != nil {
		return 0, err
	}
	if err := WriteCatalog(primary, models, reference); err != nil {
		return 0, err
	}
	if err := b.Reload(); err != nil {
		return 0, err
	}
	return len(models), nil
}

// CatalogAge reports how long ago the primary table was written. A zero
// duration means the age is unknown.
func (b *Book) CatalogAge() time.Duration {
	b.mu.RLock()
	primary := b.primary
	b.mu.RUnlock()
	fi, err := os.Stat(primary)
	if err != nil {
		return 0
	}
	return time.Since(fi.ModTime())
}
