// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wservice} from '../models';
import {prices} from '../models';
import {app} from '../models';
import {context} from '../models';

export function AbortCurrent():Promise<void>;

export function ActiveSession():Promise<string>;

export function Advice():Promise<wservice.AdviceInfo>;

export function AllowMoreSession(arg1:number,arg2:number):Promise<void>;

export function ApplyPriceOverride(arg1:string,arg2:prices.Rate):Promise<void>;

export function AvailableModels():Promise<Array<wservice.ModelOption>>;

export function ClearPriceOverrides():Promise<void>;

export function CycleDock():Promise<string>;

export function DebugLog(arg1:string):Promise<void>;

export function Disable():Promise<void>;

export function DismissAlert():Promise<void>;

export function Docks():Promise<Array<string>>;

export function ExportCsv():Promise<string>;

export function HideToTray():Promise<void>;

export function Minimise():Promise<void>;

export function ModelSwitchStatus(arg1:string):Promise<app.ModelSwitch>;

export function PendingPriceSuggestions():Promise<Array<prices.PriceSuggestion>>;

export function Preferences():Promise<app.Preferences>;

export function PreviewPrice(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<app.PricePreview>;

export function PricesAgeHours():Promise<number>;

export function Quit():Promise<void>;

export function RaiseLimit():Promise<void>;

export function Ready():Promise<void>;

export function RefreshPrices():Promise<string>;

export function ReloadPrices():Promise<void>;

export function ResetTrip():Promise<void>;

export function SavePosition(arg1:number,arg2:number):Promise<void>;

export function SetCompact(arg1:boolean):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDock(arg1:string):Promise<string>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function SetLimit(arg1:number):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetPeek(arg1:boolean):Promise<void>;

export function SetPreferences(arg1:app.Preferences):Promise<void>;

export function SetScreenSize(arg1:number,arg2:number):Promise<void>;

export function ShowAlert():Promise<void>;

export function ShowFromTray():Promise<void>;

export function SkipPrice(arg1:string):Promise<void>;

export function Snapshot():Promise<wservice.Snapshot>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function SwitchModel(arg1:string,arg2:string):Promise<app.ModelSwitch>;

export function PendingModelSwitch(arg1:string):Promise<app.ModelSwitch>;

export function ClearModelSwitch(arg1:string):Promise<void>;

export function ToggleDock():Promise<boolean>;

export function TogglePause():Promise<void>;

export function ToggleViewMode():Promise<void>;

export function UnlockSession(arg1:string,arg2:string):Promise<void>;
