// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortCurrent() {
  return window['go']['wservice']['Service']['AbortCurrent']();
}

export function ActiveSession() {
  return window['go']['wservice']['Service']['ActiveSession']();
}

export function Advice() {
  return window['go']['wservice']['Service']['Advice']();
}

export function AllowMoreSession(arg1, arg2) {
  return window['go']['wservice']['Service']['AllowMoreSession'](arg1, arg2);
}

export function ApplyPriceOverride(arg1, arg2) {
  return window['go']['wservice']['Service']['ApplyPriceOverride'](arg1, arg2);
}

export function AvailableModels() {
  return window['go']['wservice']['Service']['AvailableModels']();
}

export function CycleDock() {
  return window['go']['wservice']['Service']['CycleDock']();
}

export function DebugLog(arg1) {
  return window['go']['wservice']['Service']['DebugLog'](arg1);
}

export function Disable() {
  return window['go']['wservice']['Service']['Disable']();
}

export function DismissAlert() {
  return window['go']['wservice']['Service']['DismissAlert']();
}

export function Docks() {
  return window['go']['wservice']['Service']['Docks']();
}

export function ExportCsv() {
  return window['go']['wservice']['Service']['ExportCsv']();
}

export function Minimise() {
  return window['go']['wservice']['Service']['Minimise']();
}

export function PendingPriceSuggestions() {
  return window['go']['wservice']['Service']['PendingPriceSuggestions']();
}

export function PricesAgeHours() {
  return window['go']['wservice']['Service']['PricesAgeHours']();
}

export function Quit() {
  return window['go']['wservice']['Service']['Quit']();
}

export function RaiseLimit() {
  return window['go']['wservice']['Service']['RaiseLimit']();
}

export function RefreshPrices() {
  return window['go']['wservice']['Service']['RefreshPrices']();
}

export function ReloadPrices() {
  return window['go']['wservice']['Service']['ReloadPrices']();
}

export function ResetTrip() {
  return window['go']['wservice']['Service']['ResetTrip']();
}

export function SavePosition(arg1, arg2) {
  return window['go']['wservice']['Service']['SavePosition'](arg1, arg2);
}

export function SetCompact(arg1) {
  return window['go']['wservice']['Service']['SetCompact'](arg1);
}

export function SetContext(arg1) {
  return window['go']['wservice']['Service']['SetContext'](arg1);
}

export function SetDock(arg1) {
  return window['go']['wservice']['Service']['SetDock'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['wservice']['Service']['SetEnabled'](arg1);
}

export function SetLimit(arg1) {
  return window['go']['wservice']['Service']['SetLimit'](arg1);
}

export function SetMode(arg1) {
  return window['go']['wservice']['Service']['SetMode'](arg1);
}

export function SetScreenSize(arg1, arg2) {
  return window['go']['wservice']['Service']['SetScreenSize'](arg1, arg2);
}

export function ShowAlert() {
  return window['go']['wservice']['Service']['ShowAlert']();
}

export function SkipPrice(arg1) {
  return window['go']['wservice']['Service']['SkipPrice'](arg1);
}

export function Snapshot() {
  return window['go']['wservice']['Service']['Snapshot']();
}

export function Start() {
  return window['go']['wservice']['Service']['Start']();
}

export function Stop() {
  return window['go']['wservice']['Service']['Stop']();
}

export function ToggleDock() {
  return window['go']['wservice']['Service']['ToggleDock']();
}

export function ToggleViewMode() {
  return window['go']['wservice']['Service']['ToggleViewMode']();
}

export function UnlockSession(arg1, arg2) {
  return window['go']['wservice']['Service']['UnlockSession'](arg1, arg2);
}
