// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortCurrent() {
  return window['go']['wservice']['Service']['AbortCurrent']();
}

export function ActiveSession() {
  return window['go']['wservice']['Service']['ActiveSession']();
}

export function Advice() {
  return window['go']['wservice']['Service']['Advice']();
}

export function AllowMoreSession(arg1, arg2) {
  return window['go']['wservice']['Service']['AllowMoreSession'](arg1, arg2);
}

export function ApplyPriceOverride(arg1, arg2) {
  return window['go']['wservice']['Service']['ApplyPriceOverride'](arg1, arg2);
}

export function AvailableModels() {
  return window['go']['wservice']['Service']['AvailableModels']();
}

export function ClearModelSwitch(arg1) {
  return window['go']['wservice']['Service']['ClearModelSwitch'](arg1);
}

export function ClearPriceOverrides() {
  return window['go']['wservice']['Service']['ClearPriceOverrides']();
}

export function CycleDock() {
  return window['go']['wservice']['Service']['CycleDock']();
}

export function DebugLog(arg1) {
  return window['go']['wservice']['Service']['DebugLog'](arg1);
}

export function Disable() {
  return window['go']['wservice']['Service']['Disable']();
}

export function DismissAlert() {
  return window['go']['wservice']['Service']['DismissAlert']();
}

export function Docks() {
  return window['go']['wservice']['Service']['Docks']();
}

export function ExportCsv() {
  return window['go']['wservice']['Service']['ExportCsv']();
}

export function FallbackModels(arg1) {
  return window['go']['wservice']['Service']['FallbackModels'](arg1);
}

export function HasMetadataKey() {
  return window['go']['wservice']['Service']['HasMetadataKey']();
}

export function HideToTray() {
  return window['go']['wservice']['Service']['HideToTray']();
}

export function IncreaseOpenSessionBudget(arg1, arg2) {
  return window['go']['wservice']['Service']['IncreaseOpenSessionBudget'](arg1, arg2);
}

export function Minimise() {
  return window['go']['wservice']['Service']['Minimise']();
}

export function ModelSwitchStatus(arg1) {
  return window['go']['wservice']['Service']['ModelSwitchStatus'](arg1);
}

export function PendingModelSwitch(arg1) {
  return window['go']['wservice']['Service']['PendingModelSwitch'](arg1);
}

export function PendingPriceSuggestions() {
  return window['go']['wservice']['Service']['PendingPriceSuggestions']();
}

export function Preferences() {
  return window['go']['wservice']['Service']['Preferences']();
}

export function PreviewPrice(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wservice']['Service']['PreviewPrice'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PricesAgeHours() {
  return window['go']['wservice']['Service']['PricesAgeHours']();
}

export function Quit() {
  return window['go']['wservice']['Service']['Quit']();
}

export function RaiseLimit() {
  return window['go']['wservice']['Service']['RaiseLimit']();
}

export function Ready() {
  return window['go']['wservice']['Service']['Ready']();
}

export function ReconcileWindowLayout() {
  return window['go']['wservice']['Service']['ReconcileWindowLayout']();
}

export function RefreshMetadata() {
  return window['go']['wservice']['Service']['RefreshMetadata']();
}

export function RefreshPrices() {
  return window['go']['wservice']['Service']['RefreshPrices']();
}

export function ReloadPrices() {
  return window['go']['wservice']['Service']['ReloadPrices']();
}

export function ResetTrip() {
  return window['go']['wservice']['Service']['ResetTrip']();
}

export function ResumeOpenSession(arg1) {
  return window['go']['wservice']['Service']['ResumeOpenSession'](arg1);
}

export function SavePosition(arg1, arg2) {
  return window['go']['wservice']['Service']['SavePosition'](arg1, arg2);
}

export function SelectOpenSession(arg1) {
  return window['go']['wservice']['Service']['SelectOpenSession'](arg1);
}

export function SetCompact(arg1) {
  return window['go']['wservice']['Service']['SetCompact'](arg1);
}

export function SetContext(arg1) {
  return window['go']['wservice']['Service']['SetContext'](arg1);
}

export function SetCounter(arg1) {
  return window['go']['wservice']['Service']['SetCounter'](arg1);
}

export function SetDock(arg1) {
  return window['go']['wservice']['Service']['SetDock'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['wservice']['Service']['SetEnabled'](arg1);
}

export function SetLimit(arg1) {
  return window['go']['wservice']['Service']['SetLimit'](arg1);
}

export function SetMetadataKey(arg1) {
  return window['go']['wservice']['Service']['SetMetadataKey'](arg1);
}

export function SetMode(arg1) {
  return window['go']['wservice']['Service']['SetMode'](arg1);
}

export function SetOpenSessionBudget(arg1, arg2, arg3, arg4) {
  return window['go']['wservice']['Service']['SetOpenSessionBudget'](arg1, arg2, arg3, arg4);
}

export function SetOpenSessionRule(arg1, arg2) {
  return window['go']['wservice']['Service']['SetOpenSessionRule'](arg1, arg2);
}

export function SetPeek(arg1) {
  return window['go']['wservice']['Service']['SetPeek'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['wservice']['Service']['SetPreferences'](arg1);
}

export function SetRuleToast(arg1) {
  return window['go']['wservice']['Service']['SetRuleToast'](arg1);
}

export function SetRuleToastSize(arg1) {
  return window['go']['wservice']['Service']['SetRuleToastSize'](arg1);
}

export function SetScreenSize(arg1, arg2) {
  return window['go']['wservice']['Service']['SetScreenSize'](arg1, arg2);
}

export function ShowAlert() {
  return window['go']['wservice']['Service']['ShowAlert']();
}

export function ShowFromTray() {
  return window['go']['wservice']['Service']['ShowFromTray']();
}

export function SkipPrice(arg1) {
  return window['go']['wservice']['Service']['SkipPrice'](arg1);
}

export function Snapshot() {
  return window['go']['wservice']['Service']['Snapshot']();
}

export function Start() {
  return window['go']['wservice']['Service']['Start']();
}

export function Stop() {
  return window['go']['wservice']['Service']['Stop']();
}

export function StopOpenSession(arg1) {
  return window['go']['wservice']['Service']['StopOpenSession'](arg1);
}

export function SwitchModel(arg1, arg2) {
  return window['go']['wservice']['Service']['SwitchModel'](arg1, arg2);
}

export function ToggleDock() {
  return window['go']['wservice']['Service']['ToggleDock']();
}

export function TogglePause() {
  return window['go']['wservice']['Service']['TogglePause']();
}

export function ToggleViewMode() {
  return window['go']['wservice']['Service']['ToggleViewMode']();
}

export function UnlockSession(arg1, arg2) {
  return window['go']['wservice']['Service']['UnlockSession'](arg1, arg2);
}
